export const ALLERGENS = [
  "celery",
  "cereals containing gluten",
  "crustaceans",
  "dairy",
  "eggs",
  "fish",
  "gluten",
  "lupin",
  "milk",
  "molluscs",
  "mustard",
  "nuts",
  "peanuts",
  "sesame",
  "soy",
  "soybeans",
  "sulphur dioxide and sulphites",
]; 